<?php
$this->headTitle('Add Event');
$this->mainMenu()->setActiveItemId('eventbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Events' => $this->url('beheer/event'),
    'Add Event' => $this->url('beheer/event', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">ADD EVENT</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="col-lg-12 col-md-12 col-sm-12">
    <!-- Event form -->
    <?php
    echo $this->partial('event/partial/form.phtml', array('form' => $form));
    ?>
    <!-- End event form -->
    <!-- Image upload -->
    <?php echo $this->partial('upload-images/partial/upload_image.phtml', array('formImage' => $formEventImage)); ?>
    <!-- End image upload -->
</div>
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="form-group">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <button type="submit" id="submit" class="btn btn-primary">Opslaan</button> 
            <a href="<?php echo $this->url['beheer/event']; ?>" class="btn btn-default" title="Annuleren">Annuleren</a>
        </div>
    </div>
</div>  
<?php echo $this->form()->closeTag($form); ?>