<?php
$this->mainMenu()->setActiveItemId('archive');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Event archief' => $this->url('beheer/event', ['action' => 'archive']),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">EVENT ARCHIEF</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Titel</th>
                <th>Datum aangemaakt</th>
                <th>Datum verwijderd</th>
                <th class="th-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($events) > 0) { ?>
                <?php foreach ($events AS $event) { ?>
                    <tr>
                        <td><?php echo $event->getTitle(); ?></td>
                        <td>
                            <?php echo(is_object($event->getDateCreated()) ? $event->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                        </td>
                        <td>
                            <?php echo(is_object($event->getDateDeleted()) ? $event->getDateDeleted()->format('d-m-Y H:m:s') : ''); ?>
                        </td>
                        <td class="td-center">
                            <a class="btn btn-sm btn-danger"
                               href="<?php echo $this->url('beheer/event', ['action' => 'delete', 'id' => $event->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            <a class="btn btn-sm btn-secondary"
                               href="<?php echo $this->url('beheer/event', ['action' => 'un-archief', 'id' => $event->getId()]); ?>">
                                <i class="fas fa-redo"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="4" class="td-center">Niks gearchiveerd.</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?= $this->paginationControl($events,
    'Sliding',
    'layout/paginator',
    array('route' => 'beheer/event', 'action' => 'archive')); ?>