<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Events archief</h2>
                </div>
                <form name="searchEvents" method="post"
                      action="<?php echo $this->url('beheer/event'); ?>">
                    <div class="row g-4">
                        <div class="col-sm-6 col-md-6 col-xl-6">
                            <a class="btn btn-primary"
                               href="<?= $this->url('beheer/event'); ?>">
                                <i class="far fas fa-guitar me-2"></i> Events
                            </a>
                        </div>
                        <div class="col-sm-4 col-md-4 col-xl-4 text-end">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                        <div class="col-sm-2 col-md-2 col-xl-2">
                            <input class="form-control" name="search" value="<?php echo $searchString; ?>"
                                   type="search"
                                   placeholder="Search" aria-label="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Startdatum</th>
                        <th>Titel</th>
                        <th>Categorie</th>
                        <th>Einddatum</th>
                        <th class="text-center"><i class="fas fa-cogs"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($events) > 0) { ?>
                        <?php foreach ($events as $event) { ?>
                            <tr>
                                <td><?php echo(is_object($event->getEventStartDate()) ? $event->getEventStartDate()->format('d-m-Y H:i:s') : ''); ?></td>
                                <td><?php echo $event->getTitle(); ?></td>
                                <td><?php echo(is_object($event->getCategory()) ? $event->getCategory()->getName() : ''); ?></td>
                                <td><?php echo(is_object($event->getEventEndDate()) ? $event->getEventEndDate()->format('d-m-Y H:i:s') : ''); ?></td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-danger"
                                       href="<?php echo $this->url('beheer/event', ['action' => 'delete', 'id' => $event->getId()]); ?>">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                    <a class="btn btn-sm btn-success"
                                       href="<?php echo $this->url('beheer/event', ['action' => 'un-archief', 'id' => $event->getId()]); ?>">
                                        <i class="fas fa-redo"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                    <tr>
                        <td class="text-center" colspan="5">Geen gearchiveerde evenementen</td>
                    </tr>

                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded mt-4 p-4">
                <?= $this->paginationControl($events,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/event', 'action' => 'archive')) ?>
            </div>
        </div>
    </div>
</div>
