<?php
$this->headTitle('Edit Event');
$this->mainMenu()->setActiveItemId('eventbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Events' => $this->url('beheer/event'),
    'Edit Event' => $this->url('beheer/event', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
    <!-- Page Header -->
    <div class="row">
        <h1 class="col">EDIT EVENT</h1>
    </div>
    <!-- Breadcrumbs -->
    <div class="row">
        <div class="col">
            <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
    </div>
<?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col">
            <!-- Event form -->
            <?php
            echo $this->partial('event/partial/form.phtml', array('form' => $form));
            ?>
            <!-- End event form -->
            <!-- Show image -->
            <?php echo $this->partial('event/partial/show_image.phtml', array('formImage' => $formEventImage, 'image' => $image, 'returnURL' => $returnURL)); ?>
            <!-- End Show image -->
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
        </div>
        <div class="col text-right">
            <a href="<?php echo $this->url['beheer/event']; ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
        </div>
    </div>
<?php echo $this->form()->closeTag($form); ?>