<div class="container-fluid pt-4 px-4">
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>
    <?= $this->formRow($form->get('csrf')); ?>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <h2 class="mb-4">Edit event</h2>
                <!-- Blog form -->
                <?= $this->partial('event/partial/form.phtml', array('form' => $form)); ?>
                <!-- End blog form -->
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <!-- Image upload -->
                <?php echo $this->partial('upload-images/partial/upload_image.phtml', array('formImage' => $formEventImage)); ?>
                <!-- End image upload -->
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formRow($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?php echo $this->url['beheer\event']; ?>" class="btn btn-primary" title="Annuleren">Annuleren</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?= $this->form()->closeTag($form); ?>
</div>