
<!-- Page Header -->
<div class="row">
    <h1 class="col">EVENT BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/event', ['action' => 'add']); ?>">
            <i class="fas fa-plus-square"></i> New Event
        </a>
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/event', ['action' => 'archive']); ?>">
            <i class="fas fa-archive"></i> Archief
        </a>
    </div>
    <div class="col-md-auto text-right">
        <form class="form-inline" name="searchEvents" method="post" action="<?php echo $this->url('beheer/event'); ?>">
            <div class="col text-right" style="padding-right:0;">
                <input class="form-control" name="search" value="<?php echo $searchString; ?>" type="search"
                       placeholder="Search" aria-label="Search">
                <button class="btn btn-secondary" type="submit">Search</button>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Startdatum</th>
                <th>Titel</th>
                <th>Categorie</th>
                <th>Einddatum</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($events AS $event) { ?>
                <tr>
                    <td><?php echo(is_object($event->getEventStartDate()) ? $event->getEventStartDate()->format('d-m-Y H:i:s') : ''); ?></td>
                    <td><?php echo $event->getTitle(); ?></td>
                    <td><?php echo(is_object($event->getCategory()) ? $event->getCategory()->getName() : ''); ?></td>
                    <td><?php echo(is_object($event->getEventEndDate()) ? $event->getEventEndDate()->format('d-m-Y H:i:s') : ''); ?></td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-secondary" title="Edit event" href="
                       <?= $this->url('beheer/event', ['action' => 'edit', 'id' => $event->getId()]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-secondary" title="Archiveer event" href="
                       <?= $this->url('beheer/event', ['action' => 'archief', 'id' => $event->getId()]); ?>">
                            <i class="fas fa-archive"></i>
                        </a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?= $this->paginationControl($events,
    'Sliding',
    'layout/paginator',
    array('route' => 'beheer/event')); ?>