<?php
$this->mainMenu()->setActiveItemId('eventbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Events' => $this->url('beheer/event'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">CONTACT BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <a class="btn btn-default" href="
       <?= $this->url('beheer/event', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Event
    </a>
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-bordered table-hover">
        <tr>
            <th>Startdatum</th>
            <th>Titel</th>
            <th>Categorie</th>
            <th>Einddatum</th>
            <th class="text-center"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
        <?php foreach ($events AS $event) { ?>
            <tr>
                <td><?php echo (is_object($event->getEventStartDate()) ? $event->getEventStartDate()->format('d-m-Y H:i:s') : ''); ?></td>
                <td><?php echo $event->getTitle(); ?></td>
                <td><?php echo (is_object($event->getCategory())? $event->getCategory()->getName(): ''); ?></td>
                <td><?php echo (is_object($event->getEventEndDate()) ? $event->getEventEndDate()->format('d-m-Y H:i:s') : ''); ?></td>
                <td class="td-center">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/event', ['action' => 'edit', 'id' => $event->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/event', ['action' => 'archief', 'id' => $event->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Archiveer
                        </a>
                    </td>
            </tr>
        <?php } ?>
    </table>
</div>