<?php
$this->headTitle('Add Event Category');
$this->mainMenu()->setActiveItemId('eventbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Event Categories' => $this->url('beheer/eventcategories'),
    'Add Event Category' => $this->url('beheer/eventcategories', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">ADD EVENT CATEGORY</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="col-lg-12 col-md-12 col-sm-12">
    <!-- Event category form -->
    <?php
    echo $this->partial('event/partial/form_category.phtml', array('form' => $form));
    ?>
    <!-- End event category form -->
</div>
<div class="col-sm-12 col-md-12 col-lg-12 " style="padding-left:0;">
    <div class="form-group">
        <button type="submit" id="submit" class="btn btn-primary">Opslaan</button> 
        <a href="<?php echo $this->url['beheer/eventcategories']; ?>" class="btn btn-default" title="Annuleren">Annuleren</a>
    </div>
</div>  
<?php echo $this->form()->closeTag($form); ?>