<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Event categories archief</h2>
                </div>
                <form name="searchEvents" method="post"
                      action="<?php echo $this->url('beheer/eventcategories', ['action' => 'archive']); ?>">
                    <div class="row g-4">
                        <div class="col-sm-6 col-md-6 col-xl-6">
                            <a class="btn btn-primary"
                               href="<?= $this->url('beheer/eventcategories', ['action' => 'index']); ?>">
                                <i class="far fas fa-sitemap"></i> Categorie&euml;n
                            </a>
                        </div>
                        <div class="col-sm-4 col-md-4 col-xl-4 text-end">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                        <div class="col-sm-2 col-md-2 col-xl-2">
                            <input class="form-control" name="search" value="<?php echo $searchString; ?>"
                                   type="search"
                                   placeholder="Search" aria-label="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Titel</th>
                        <th>Datum aangemaakt</th>
                        <th>Datum verwijderd</th>
                        <th class="th-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($eventCategories ?? []) > 0) { ?>
                        <?php foreach ($eventCategories as $event) { ?>
                            <tr>
                                <td><?php echo $event->getName(); ?></td>
                                <td>
                                    <?php echo(is_object($event->getDateCreated()) ? $event->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                                </td>
                                <td>
                                    <?php echo(is_object($event->getDateDeleted()) ? $event->getDateDeleted()->format('d-m-Y H:m:s') : ''); ?>
                                </td>
                                <td class="td-center">
                                    <a class="btn btn-sm btn-primary" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'delete', 'id' => $event->getId()]); ?>">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>

                                    <a class="btn btn-sm btn-warning" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'un-archief', 'id' => $event->getId()]); ?>">
                                         <i class="fas fa-undo"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="4" class="td-center">Niks gearchiveerd.</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
