<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Events</h2>
                </div>
                <form name="searchEvents" method="post"
                      action="<?php echo $this->url('beheer/eventcategories'); ?>">
                    <div class="row g-4">
                        <div class="col-sm-6 col-md-6 col-xl-6">
                            <a class="btn btn-primary" href="<?= $this->url('beheer/eventcategories', ['action' => 'add']); ?>">
                                <i class="fas fa-plus"></i> New Category
                            </a>
                            <a class="btn btn-primary"
                               href="<?= $this->url('beheer/eventcategories', ['action' => 'archive']); ?>">
                                <i class="fas fa-archive"></i> Archief
                            </a>
                        </div>
                        <div class="col-sm-4 col-md-4 col-xl-4 text-end">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                        <div class="col-sm-2 col-md-2 col-xl-2">
                            <input class="form-control" name="search" value="<?php echo $searchString; ?>"
                                   type="search"
                                   placeholder="Search" aria-label="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Naam</th>
                        <th class="text-center"><span class="glyphicon glyphicon-cog"></span></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($eventCategories as $eventCategory) { ?>
                        <tr>
                            <td><?php echo $eventCategory->getName(); ?></td>
                            <td class="td-center">
                                <a class="btn btn-sm btn-warning" title="Edit" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'edit', 'id' => $eventCategory->getId()]); ?>">
                                    <span class="fas fa-edit" aria-hidden="true"></span>
                                </a>
                                &nbsp;
                                <a class="btn btn-sm btn-primary" title="Archiveer" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'archief', 'id' => $eventCategory->getId()]); ?>">
                                    <i class="fas fa-archive"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
