<?php
$this->headTitle('Event Categories');
$this->mainMenu()->setActiveItemId('eventbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Event categories' => $this->url('beheer/eventcategories'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">EVENT CATEGORIES BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <a class="btn btn-default" href="
       <?= $this->url('beheer/eventcategories', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Category
    </a>
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-bordered table-hover">
        <tr>
            <th>Naam</th>
            <th class="text-center"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
        <?php foreach ($eventCategories AS $eventCategory) { ?>
            <tr>
                <td><?php echo $eventCategory->getName(); ?></td>
                <td class="td-center">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'edit', 'id' => $eventCategory->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/eventcategories', ['action' => 'archief', 'id' => $eventCategory->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Archiveer
                        </a>
                    </td>
            </tr>
        <?php } ?>
    </table>
</div>