<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" id="eventBackground">
                <h5 class="modal-title event-title text-center" id="eventTitle"></h5>
                <span class="closeEvent"><i class="fas fa-times"></i></span>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col text-left" id="startDate"></div>
                    <div class="col text-center" id="eventCategory"></div>
                    <div class="col text-right" id="endDate"></div>
                </div>
                <div class="row">
                    <div class="col" id="mainText"></div>
                </div>
            </div>
        </div>
    </div>
</div>