<?php
$fieldset = $form->get('event');
$title = $fieldset->get('title');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($title) ?>
        <?= $this->formElement($title) ?>
    </div>
</div>

<?php $eventStartDate = $fieldset->get('eventStartDate'); ?>
<div class="row mb-2">
    <div class="col-md-auto">
        <?= $this->formLabel($eventStartDate) ?>
        <div class="input-group mb-2 mt-2 date" id='datetimepicker1'>
            <?= $this->formText($eventStartDate); ?>
            <small class="form-text text-danger"> <?= $this->formElementErrors()->render($eventStartDate) ?></small>
        </div>
    </div>
    <?php $eventStartTime = $fieldset->get('eventStartTime'); ?>
    <div class="col-md-auto">
        <?= $this->formHidden($eventStartTime) ?>
    </div>
</div>
<?php $eventEndDate = $fieldset->get('eventEndDate'); ?>
<div class="row mb-2">
    <div class="col-md-auto">

        <?= $this->formLabel($eventEndDate) ?>
        <div class="input-group mb-2 mt-2 date" id='datetimepicker2'>
            <?= $this->formText($eventEndDate); ?>
            <small class="form-text text-danger"> <?= $this->formElementErrors()->render($eventEndDate) ?></small>
        </div>
    </div>
    <?php $eventEndTime = $fieldset->get('eventEndTime'); ?>
    <div class="col-md-auto">
        <?= $this->formHidden($eventEndTime); ?>
    </div>
</div>
<?php $category = $fieldset->get('category'); ?>
<div class="row mb-4">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formElement($category) ?>
    </div>
    <small class="form-text text-danger"> <?= $this->formElementErrors()->render($category) ?></small>
</div>
<!-- Google maps -->
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?php
        echo $this->partial('event/partial/google_maps.phtml');
        $longitude = $fieldset->get('longitude');
        ?>
    </div>
</div>

<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($longitude) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-6 col-md-6 col-xl-6">
        <label class="sr-only" for="inlineFormInputGroup">Longitude</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
            </div>
            <?= $this->formElement($longitude) ?>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-xl-6">
        <label class="sr-only" for="inlineFormInputGroup">Longitude</label>
        <div class="input-group mb-2">
            <input type="text" class="form-control" id="longmoved" value="" readonly="readonly"/>
            <div class="input-group-append">
                <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
            </div>
        </div>
    </div>
</div>
<?php
$latitude = $fieldset->get('latitude');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($latitude) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-6 col-md-6 col-xl-6">
        <label class="sr-only" for="inlineFormInputGroup">Latitude</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
            </div>
            <?= $this->formElement($latitude) ?>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-xl-6">
        <label class="sr-only" for="inlineFormInputGroup">Longitude</label>
        <div class="input-group mb-2">
            <input type="text" class="form-control" id="latmoved" value="" readonly="readonly"/>
            <div class="input-group-append">
                <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
            </div>
        </div>
    </div>
</div>
<!-- End Google Maps -->
<?php
$labelText = $fieldset->get('labelText');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($labelText) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formElement($labelText) ?>
    </div>
</div>
<?php
$text = $fieldset->get('text');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($text) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formElement($text) ?>
    </div>
</div>
