<?php
$fieldset = $form->get('event-category-fieldset');
?>
<?php
$name = $fieldset->get('name');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($name) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formElement($name) ?>
    </div>
</div>
<?php
$description = $fieldset->get('description');
?>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formLabel($description) ?>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <?= $this->formElement($description) ?>
    </div>
</div>
